# This access_token is a User access token w/ permission to access API
access_token: #populate

page_total: 100   # Should be a maximum of 1,000
search_total: 100   # You can query a maximum of 5,000 ads

ad_active_status: ALL   # ACTIVE, INACTIVE, or ALL

# You can provide search terms and/or page IDs.
#search_terms: aoc
search_page_ids:
  - !!str 612471195588500 # - burrow
  - !!str 70267159212 # - lands end
  - !!str 70267159212 # - fashion to figure
  - !!str 75681651558 # - talbots
  - !!str 179450065439629 # - chewy

# Extra brand page IDs:
  # !!str 2009466829272479 - fenty
  # !!str 10236898932 - torrid
  # !!str 25297200265 - vans
  # !!str 23402039579 - converse
  # !!str 7133041750 - pacsun
  # !!str 95181800661 - levis
  # !!str 20395377020 - old navy
  # !!str 612471195588500 - burrow
  # !!str 70267159212 - lands end
  # !!str 70267159212 - fashion to figure
  # !!str 75681651558 - talbots
  # !!str 179450065439629 - chewy


# Fields for querying all possible metadata from the API
# These are v22.0 field names
query_fields:
  - id
  - ad_creation_time
  - ad_creative_bodies
  - ad_creative_link_titles
  - ad_creative_link_captions
  - ad_creative_link_descriptions
  - ad_delivery_start_time
  - ad_delivery_stop_time
  - ad_snapshot_url
  - demographic_distribution
  - impressions
  - spend
  - page_id
  - page_name
  - publisher_platforms
  - languages
  - ad_creative_link_url
  - effective_status
  - created_time
  - updated_time
  - body
  - status
  - is_active
  - link_url
  - title
  - caption
  - description

# Fields which are included in the main CSV, including derived fields
output_fields:
  - ad_id
  - page_id
  - page_name
  - promotional_text
  - ad_delivery_start_time
  - ad_delivery_stop_time
  - ad_creation_time
  - created_time
  - updated_time
  - ad_creative_bodies
  - status
  - effective_status
  - ad_active_status
  - is_active
  - body
  - title
  - caption
  - description
  # - ad_creative_links
  # - ad_creative_link_titles
  # - ad_creative_link_captions
  # - ad_creative_link_descriptions
  - link_url
  - image_name
  - image_link
  - image_description
  - impressions_min
  - impressions_max
  - spend_min
  - spend_max
  - ad_url
  - publisher_platforms
  - languages

# Fields for the unnested CSVs
demo_fields:
  - ad_id
  - age
  - gender
  - percentage

region_fields:
  - ad_id
  - region
  - percentage

demo_ages:
  - 18-24
  - 25-34
  - 35-44
  - 45-54
  - 55-64
  - 65+

demo_genders:
  - male
  - female
  - unknown

regions:
  - Alabama
  - Arkansas
  - California
  - Connecticut
  - Florida
  - Georgia
  - Idaho
  - Illinois
  - Indiana
  - Kansas
  - Kentucky
  - Maryland
  - Massachusetts
  - Minnesota
  - Mississippi
  - Nebraska
  - New Jersey
  - New Mexico
  - New York
  - North Carolina
  - Ohio
  - Oregon
  - South Carolina
  - South Dakota
  - Tennessee
  - Virginia
  - Washington
  - West Virginia
  - Montana
  - Pennsylvania
  - Wisconsin
  - Alaska
  - Arizona
  - Colorado
  - Delaware
  - Washington, District of Columbia
  - Hawaii
  - Iowa
  - Louisiana
  - Maine
  - Michigan
  - Missouri
  - North Dakota
  - Oklahoma
  - Rhode Island
  - Nevada
  - New Hampshire
  - Texas
  - Utah
  - Vermont
  - Wyoming